/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LavanderiaRouteImport } from './routes/lavanderia'
import { Route as EntradaRouteImport } from './routes/entrada'
import { Route as EdificiosRouteImport } from './routes/edificios'
import { Route as ChoupanasRouteImport } from './routes/choupanas'
import { Route as BrinquedotecaRouteImport } from './routes/brinquedoteca'
import { Route as BicicletarioRouteImport } from './routes/bicicletario'
import { Route as AcessibilidadeRouteImport } from './routes/acessibilidade'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as IndexRouteImport } from './routes/index'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LavanderiaRoute = LavanderiaRouteImport.update({
  id: '/lavanderia',
  path: '/lavanderia',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const EdificiosRoute = EdificiosRouteImport.update({
  id: '/edificios',
  path: '/edificios',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoupanasRoute = ChoupanasRouteImport.update({
  id: '/choupanas',
  path: '/choupanas',
  getParentRoute: () => rootRouteImport,
} as any)
const BrinquedotecaRoute = BrinquedotecaRouteImport.update({
  id: '/brinquedoteca',
  path: '/brinquedoteca',
  getParentRoute: () => rootRouteImport,
} as any)
const BicicletarioRoute = BicicletarioRouteImport.update({
  id: '/bicicletario',
  path: '/bicicletario',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessibilidadeRoute = AcessibilidadeRouteImport.update({
  id: '/acessibilidade',
  path: '/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/bicicletario': typeof BicicletarioRoute
  '/brinquedoteca': typeof BrinquedotecaRoute
  '/choupanas': typeof ChoupanasRoute
  '/edificios': typeof EdificiosRoute
  '/entrada': typeof EntradaRoute
  '/lavanderia': typeof LavanderiaRoute
  '/mapa': typeof MapaRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/bicicletario': typeof BicicletarioRoute
  '/brinquedoteca': typeof BrinquedotecaRoute
  '/choupanas': typeof ChoupanasRoute
  '/edificios': typeof EdificiosRoute
  '/entrada': typeof EntradaRoute
  '/lavanderia': typeof LavanderiaRoute
  '/mapa': typeof MapaRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/bicicletario': typeof BicicletarioRoute
  '/brinquedoteca': typeof BrinquedotecaRoute
  '/choupanas': typeof ChoupanasRoute
  '/edificios': typeof EdificiosRoute
  '/entrada': typeof EntradaRoute
  '/lavanderia': typeof LavanderiaRoute
  '/mapa': typeof MapaRoute
  '/menu': typeof MenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/acessibilidade'
    | '/bicicletario'
    | '/brinquedoteca'
    | '/choupanas'
    | '/edificios'
    | '/entrada'
    | '/lavanderia'
    | '/mapa'
    | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/acessibilidade'
    | '/bicicletario'
    | '/brinquedoteca'
    | '/choupanas'
    | '/edificios'
    | '/entrada'
    | '/lavanderia'
    | '/mapa'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/acessibilidade'
    | '/bicicletario'
    | '/brinquedoteca'
    | '/choupanas'
    | '/edificios'
    | '/entrada'
    | '/lavanderia'
    | '/mapa'
    | '/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  AcessibilidadeRoute: typeof AcessibilidadeRoute
  BicicletarioRoute: typeof BicicletarioRoute
  BrinquedotecaRoute: typeof BrinquedotecaRoute
  ChoupanasRoute: typeof ChoupanasRoute
  EdificiosRoute: typeof EdificiosRoute
  EntradaRoute: typeof EntradaRoute
  LavanderiaRoute: typeof LavanderiaRoute
  MapaRoute: typeof MapaRoute
  MenuRoute: typeof MenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavanderia': {
      id: '/lavanderia'
      path: '/lavanderia'
      fullPath: '/lavanderia'
      preLoaderRoute: typeof LavanderiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrada': {
      id: '/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof EntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edificios': {
      id: '/edificios'
      path: '/edificios'
      fullPath: '/edificios'
      preLoaderRoute: typeof EdificiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choupanas': {
      id: '/choupanas'
      path: '/choupanas'
      fullPath: '/choupanas'
      preLoaderRoute: typeof ChoupanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brinquedoteca': {
      id: '/brinquedoteca'
      path: '/brinquedoteca'
      fullPath: '/brinquedoteca'
      preLoaderRoute: typeof BrinquedotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bicicletario': {
      id: '/bicicletario'
      path: '/bicicletario'
      fullPath: '/bicicletario'
      preLoaderRoute: typeof BicicletarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessibilidade': {
      id: '/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/acessibilidade'
      preLoaderRoute: typeof AcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  AcessibilidadeRoute: AcessibilidadeRoute,
  BicicletarioRoute: BicicletarioRoute,
  BrinquedotecaRoute: BrinquedotecaRoute,
  ChoupanasRoute: ChoupanasRoute,
  EdificiosRoute: EdificiosRoute,
  EntradaRoute: EntradaRoute,
  LavanderiaRoute: LavanderiaRoute,
  MapaRoute: MapaRoute,
  MenuRoute: MenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
